name: CI - Web

on:
  push:
    branches:
      - main
    paths:
      - 'web/**'
  pull_request:
    branches:
      - main
    paths:
      - 'web/**'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: web
